# readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# taken from https://github.com/readthedocs-examples/example-mkdocs-basic/blob/main/.readthedocs.yaml

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  source_dir: docs

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
   system_packages: true
   system_site_packages: true
   packages:
     - printipy.api
