site_name: PrintiPy

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - how-to-guides.md
  - API Reference: reference.md
  - Data Objects: data-objects.md
  - API Exceptions: exceptions.md
  - explanation.md
